import Head from 'next/head';
import './_layout.module.scss';
import Header from './Header/Header';
import Footer from './Footer/Footer';

const Layout = ({ children }) => (
	<>
		<Head>
			<meta charset="utf-8" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<title>MochiVideo - Học tiếng Anh miễn phí qua Video cùng MochiMochi</title>
			<meta name="title" content="MochiVideo - Học tiếng Anh miễn phí qua Video cùng MochiMochi" />
			<meta name="description" content="Trang web hỗ trợ học từ vựng tiếng Anh miễn phí thông qua video thuộc các chủ đề đa dạng. Tra từ không giới hạn trực tiếp trên trang và lưu từ vào tài khoản học MochiMochi." />
			<meta property="og:description" content="Trang web hỗ trợ học từ vựng tiếng Anh miễn phí thông qua video thuộc các chủ đề đa dạng. Tra từ không giới hạn trực tiếp trên trang và lưu từ vào tài khoản học MochiMochi." />
			<meta property="og:image" content="/MOCHIVIDEO.jpg" />
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/mochi.ico" />
			<link
				rel="stylesheet"
				type="text/css"
				charset="UTF-8"
				href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
			/>
			<link
				rel="stylesheet"
				type="text/css"
				href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
			/>
		</Head>

		<Header />
			<div>{children}</div>
		<Footer />
	</>
);

export default Layout;
